// AUTO-GENERATED by scripts/generate-stun-root-questions.mjs — do not edit by hand.
// Source: Meraki Analytics champion data (cdn.merakianalytics.com), cross-referenced
// against Data Dragon patch 16.17.1 for the champion roster.
// Only includes stun/root durations that are constant across every rank.
// Re-run the script to regenerate after a balance patch.
import { Question } from "@/lib/quiz-types";

export const stunRootQuestions: Question[] = [
  {
    "id": "amumu-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Amumu",
    "championId": "Amumu",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Bandage Toss (Q)",
    "text": "What is Bandage Toss's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "amumu-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Amumu",
    "championId": "Amumu",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Curse of the Sad Mummy (R)",
    "text": "What is Curse of the Sad Mummy's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "alistar-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Alistar",
    "championId": "Alistar",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Pulverize (Q)",
    "text": "What is Pulverize's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "alistar-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Alistar",
    "championId": "Alistar",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Headbutt (W)",
    "text": "What is Headbutt's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "alistar-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Alistar",
    "championId": "Alistar",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Trample (E)",
    "text": "What is Trample's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "aphelios-r-root-duration",
    "type": "multiple-choice",
    "champion": "Aphelios",
    "championId": "Aphelios",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Moonlight Vigil (R)",
    "text": "What is Moonlight Vigil's (GRAVITUM) root duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.35s",
      "1.5s"
    ],
    "answer": "1.35s"
  },
  {
    "id": "ambessa-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Ambessa",
    "championId": "Ambessa",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Public Execution (R)",
    "text": "What is Public Execution's stun duration?",
    "choices": [
      "0.25s",
      "0.4s",
      "0.5s",
      "0.75s"
    ],
    "answer": "0.4s"
  },
  {
    "id": "aurelionsol-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Aurelion Sol",
    "championId": "AurelionSol",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Falling Star (R)",
    "text": "What is Falling Star's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "blitzcrank-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Blitzcrank",
    "championId": "Blitzcrank",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Rocket Grab (Q)",
    "text": "What is Rocket Grab's stun duration?",
    "choices": [
      "0.5s",
      "0.65s",
      "0.75s",
      "1s"
    ],
    "answer": "0.65s"
  },
  {
    "id": "briar-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Briar",
    "championId": "Briar",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Head Rush (Q)",
    "text": "What is Head Rush's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "0.85s",
      "1s"
    ],
    "answer": "0.85s"
  },
  {
    "id": "briar-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Briar",
    "championId": "Briar",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Chilling Scream (E)",
    "text": "What is Chilling Scream's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "caitlyn-w-root-duration",
    "type": "multiple-choice",
    "champion": "Caitlyn",
    "championId": "Caitlyn",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Yordle Snap Trap (W)",
    "text": "What is Yordle Snap Trap's root duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "ekko-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Ekko",
    "championId": "Ekko",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Parallel Convergence (W)",
    "text": "What is Parallel Convergence's stun duration?",
    "choices": [
      "1.75s",
      "2s",
      "2.25s",
      "2.5s"
    ],
    "answer": "2.25s"
  },
  {
    "id": "gragas-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Gragas",
    "championId": "Gragas",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Body Slam (E)",
    "text": "What is Body Slam's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "hecarim-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Hecarim",
    "championId": "Hecarim",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Devastating Charge (E)",
    "text": "What is Devastating Charge's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.25s"
  },
  {
    "id": "heimerdinger-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Heimerdinger",
    "championId": "Heimerdinger",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "CH-2 Electron Storm Grenade (E)",
    "text": "What is CH-2 Electron Storm Grenade's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "irelia-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Irelia",
    "championId": "Irelia",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Flawless Duet (E)",
    "text": "What is Flawless Duet's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "jinx-e-root-duration",
    "type": "multiple-choice",
    "champion": "Jinx",
    "championId": "Jinx",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Flame Chompers! (E)",
    "text": "What is Flame Chompers!'s root duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "jax-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Jax",
    "championId": "Jax",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Counter Strike (E)",
    "text": "What is Counter Strike's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "ksante-q-stun-duration",
    "type": "multiple-choice",
    "champion": "K'Sante",
    "championId": "KSante",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ntofo Strikes (Q)",
    "text": "What is Ntofo Strikes's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "0.8s",
      "1s"
    ],
    "answer": "0.8s"
  },
  {
    "id": "ksante-r-stun-duration",
    "type": "multiple-choice",
    "champion": "K'Sante",
    "championId": "KSante",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "All Out (R)",
    "text": "What is All Out's stun duration?",
    "choices": [
      "0.25s",
      "0.3s",
      "0.5s",
      "0.75s"
    ],
    "answer": "0.3s"
  },
  {
    "id": "ksante-r-root-duration",
    "type": "multiple-choice",
    "champion": "K'Sante",
    "championId": "KSante",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "All Out (R)",
    "text": "What is All Out's root duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "ksante-r-stun-duration-2",
    "type": "multiple-choice",
    "champion": "K'Sante",
    "championId": "KSante",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "All Out (R)",
    "text": "What is All Out's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "kennen-p-stun-duration",
    "type": "multiple-choice",
    "champion": "Kennen",
    "championId": "Kennen",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Mark of the Storm (Passive)",
    "text": "What is Mark of the Storm's stun duration?",
    "choices": [
      "0.75s",
      "1s",
      "1.25s",
      "1.5s"
    ],
    "answer": "1.25s"
  },
  {
    "id": "leblanc-e-root-duration",
    "type": "multiple-choice",
    "champion": "LeBlanc",
    "championId": "Leblanc",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ethereal Chains (E)",
    "text": "What is Ethereal Chains's root duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "leona-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Leona",
    "championId": "Leona",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Shield of Daybreak (Q)",
    "text": "What is Shield of Daybreak's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "lissandra-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Lissandra",
    "championId": "Lissandra",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Frozen Tomb (R)",
    "text": "What is Frozen Tomb's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "lux-q-root-duration",
    "type": "multiple-choice",
    "champion": "Lux",
    "championId": "Lux",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Light Binding (Q)",
    "text": "What is Light Binding's root duration?",
    "choices": [
      "1.5s",
      "1.75s",
      "2s",
      "2.5s"
    ],
    "answer": "2s"
  },
  {
    "id": "maokai-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Maokai",
    "championId": "Maokai",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Bramble Smash (Q)",
    "text": "What is Bramble Smash's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "nautilus-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Nautilus",
    "championId": "Nautilus",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Dredge Line (Q)",
    "text": "What is Dredge Line's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "neeko-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Neeko",
    "championId": "Neeko",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Pop Blossom (R)",
    "text": "What is Pop Blossom's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "orianna-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Orianna",
    "championId": "Orianna",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Command: Shockwave (R)",
    "text": "What is Command: Shockwave's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "ornn-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Ornn",
    "championId": "Ornn",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Searing Charge (E)",
    "text": "What is Searing Charge's stun duration?",
    "choices": [
      "0.75s",
      "1s",
      "1.25s",
      "1.5s"
    ],
    "answer": "1.25s"
  },
  {
    "id": "ornn-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Ornn",
    "championId": "Ornn",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Call of the Forge God (R)",
    "text": "What is Call of the Forge God's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "pantheon-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Pantheon",
    "championId": "Pantheon",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Shield Vault (W)",
    "text": "What is Shield Vault's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "rammus-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Rammus",
    "championId": "Rammus",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Powerball (Q)",
    "text": "What is Powerball's stun duration?",
    "choices": [
      "0.25s",
      "0.4s",
      "0.5s",
      "0.75s"
    ],
    "answer": "0.4s"
  },
  {
    "id": "rell-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Rell",
    "championId": "Rell",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Shattering Strike (Q)",
    "text": "What is Shattering Strike's stun duration?",
    "choices": [
      "0.5s",
      "0.65s",
      "0.75s",
      "1s"
    ],
    "answer": "0.65s"
  },
  {
    "id": "rell-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Rell",
    "championId": "Rell",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ferromancy: Crash Down (W)",
    "text": "What is Ferromancy: Crash Down's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "0.8s",
      "1s"
    ],
    "answer": "0.8s"
  },
  {
    "id": "renata-q-root-duration",
    "type": "multiple-choice",
    "champion": "Renata Glasc",
    "championId": "Renata",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Handshake (Q)",
    "text": "What is Handshake's root duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "renata-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Renata Glasc",
    "championId": "Renata",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Handshake (Q)",
    "text": "What is Handshake's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "renekton-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Renekton",
    "championId": "Renekton",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ruthless Predator (W)",
    "text": "What is Ruthless Predator's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "riven-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Riven",
    "championId": "Riven",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ki Burst (W)",
    "text": "What is Ki Burst's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "sejuani-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Sejuani",
    "championId": "Sejuani",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Permafrost (E)",
    "text": "What is Permafrost's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "sejuani-r-stun-duration-2",
    "type": "multiple-choice",
    "champion": "Sejuani",
    "championId": "Sejuani",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Glacial Prison (R)",
    "text": "What is Glacial Prison's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "sett-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Sett",
    "championId": "Sett",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Facebreaker (E)",
    "text": "What is Facebreaker's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "sona-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Sona",
    "championId": "Sona",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Crescendo (R)",
    "text": "What is Crescendo's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "skarner-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Skarner",
    "championId": "Skarner",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Ixtal's Impact (E)",
    "text": "What is Ixtal's Impact's stun duration?",
    "choices": [
      "0.75s",
      "1s",
      "1.1s",
      "1.25s"
    ],
    "answer": "1.1s"
  },
  {
    "id": "sion-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Sion",
    "championId": "Sion",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Unstoppable Onslaught (R)",
    "text": "What is Unstoppable Onslaught's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "swain-e-root-duration",
    "type": "multiple-choice",
    "champion": "Swain",
    "championId": "Swain",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Nevermove (E)",
    "text": "What is Nevermove's root duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "syndra-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Syndra",
    "championId": "Syndra",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Scatter the Weak (E)",
    "text": "What is Scatter the Weak's stun duration?",
    "choices": [
      "0.75s",
      "1s",
      "1.25s",
      "1.5s"
    ],
    "answer": "1.25s"
  },
  {
    "id": "tahmkench-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Tahm Kench",
    "championId": "TahmKench",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Tongue Lash (Q)",
    "text": "What is Tongue Lash's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "tahmkench-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Tahm Kench",
    "championId": "TahmKench",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Abyssal Dive (W)",
    "text": "What is Abyssal Dive's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "taliyah-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Taliyah",
    "championId": "Taliyah",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Unraveled Earth (E)",
    "text": "What is Unraveled Earth's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "taric-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Taric",
    "championId": "Taric",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Dazzle (E)",
    "text": "What is Dazzle's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "thresh-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Thresh",
    "championId": "Thresh",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Death Sentence (Q)",
    "text": "What is Death Sentence's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "udyr-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Udyr",
    "championId": "Udyr",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Blazing Stampede (E)",
    "text": "What is Blazing Stampede's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "vayne-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Vayne",
    "championId": "Vayne",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Condemn (E)",
    "text": "What is Condemn's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "urgot-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Urgot",
    "championId": "Urgot",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Disdain (E)",
    "text": "What is Disdain's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "velkoz-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Vel'Koz",
    "championId": "Velkoz",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Tectonic Disruption (E)",
    "text": "What is Tectonic Disruption's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "varus-r-root-duration",
    "type": "multiple-choice",
    "champion": "Varus",
    "championId": "Varus",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Chain of Corruption (R)",
    "text": "What is Chain of Corruption's root duration?",
    "choices": [
      "1.5s",
      "1.75s",
      "2s",
      "2.5s"
    ],
    "answer": "2s"
  },
  {
    "id": "vi-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Vi",
    "championId": "Vi",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Cease and Desist (R)",
    "text": "What is Cease and Desist's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.75s"
  },
  {
    "id": "viktor-w-stun-duration",
    "type": "multiple-choice",
    "champion": "Viktor",
    "championId": "Viktor",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Gravity Field (W)",
    "text": "What is Gravity Field's stun duration?",
    "choices": [
      "1s",
      "1.25s",
      "1.5s",
      "1.75s"
    ],
    "answer": "1.5s"
  },
  {
    "id": "xayah-e-root-duration",
    "type": "multiple-choice",
    "champion": "Xayah",
    "championId": "Xayah",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Bladecaller (E)",
    "text": "What is Bladecaller's root duration?",
    "choices": [
      "0.75s",
      "1s",
      "1.25s",
      "1.5s"
    ],
    "answer": "1.25s"
  },
  {
    "id": "volibear-q-stun-duration",
    "type": "multiple-choice",
    "champion": "Volibear",
    "championId": "Volibear",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Thundering Smash (Q)",
    "text": "What is Thundering Smash's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "yone-r-stun-duration",
    "type": "multiple-choice",
    "champion": "Yone",
    "championId": "Yone",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Fate Sealed (R)",
    "text": "What is Fate Sealed's stun duration?",
    "choices": [
      "0.5s",
      "0.75s",
      "1s",
      "1.25s"
    ],
    "answer": "1s"
  },
  {
    "id": "zac-q-root-duration",
    "type": "multiple-choice",
    "champion": "Zac",
    "championId": "Zac",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Stretching Strikes (Q)",
    "text": "What is Stretching Strikes's root duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  },
  {
    "id": "zac-e-stun-duration",
    "type": "multiple-choice",
    "champion": "Zac",
    "championId": "Zac",
    "category": "abilities",
    "difficulty": "medium",
    "ability": "Elastic Slingshot (E)",
    "text": "What is Elastic Slingshot's stun duration?",
    "choices": [
      "0.25s",
      "0.5s",
      "0.75s",
      "1s"
    ],
    "answer": "0.5s"
  }
];
